# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'INTERFACEGRAPHIQUE/UI/Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(894, 620)
        self.textBrowserLstArticle = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserLstArticle.setGeometry(QtCore.QRect(20, 50, 391, 541))
        self.textBrowserLstArticle.setObjectName("textBrowserLstArticle")
        self.labelTitle = QtWidgets.QLabel(Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(20, 10, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.labelID = QtWidgets.QLabel(Dialog)
        self.labelID.setGeometry(QtCore.QRect(440, 80, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.labelID.setFont(font)
        self.labelID.setObjectName("labelID")
        self.labelType = QtWidgets.QLabel(Dialog)
        self.labelType.setGeometry(QtCore.QRect(440, 30, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.labelType.setFont(font)
        self.labelType.setObjectName("labelType")
        self.lineEditID = QtWidgets.QLineEdit(Dialog)
        self.lineEditID.setGeometry(QtCore.QRect(690, 80, 181, 31))
        self.lineEditID.setObjectName("lineEditID")
        self.comboBoxType = QtWidgets.QComboBox(Dialog)
        self.comboBoxType.setGeometry(QtCore.QRect(690, 30, 181, 31))
        self.comboBoxType.setObjectName("comboBoxType")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.labelErreur = QtWidgets.QLabel(Dialog)
        self.labelErreur.setGeometry(QtCore.QRect(590, 460, 341, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelErreur.setFont(font)
        self.labelErreur.setStyleSheet("color: rgb(255, 0, 0);\n"
"")
        self.labelErreur.setObjectName("labelErreur")
        self.buttonAjouter = QtWidgets.QPushButton(Dialog)
        self.buttonAjouter.setGeometry(QtCore.QRect(430, 160, 93, 28))
        self.buttonAjouter.setObjectName("buttonAjouter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelTitle.setText(_translate("Dialog", "Liste des Articles :"))
        self.labelID.setText(_translate("Dialog", "ID de l\'objet à affecter:"))
        self.labelType.setText(_translate("Dialog", "Type d\'object à afficher:"))
        self.comboBoxType.setItemText(0, _translate("Dialog", "Article"))
        self.comboBoxType.setItemText(1, _translate("Dialog", "Utilisateur"))
        self.comboBoxType.setItemText(2, _translate("Dialog", "Facture"))
        self.labelErreur.setText(_translate("Dialog", "* labelErreur"))
        self.buttonAjouter.setText(_translate("Dialog", "Ajouter"))
