# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'INTERFACEGRAPHIQUE/UI/Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(768, 755)
        self.textBrowserLstArticle = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserLstArticle.setGeometry(QtCore.QRect(20, 50, 351, 311))
        self.textBrowserLstArticle.setObjectName("textBrowserLstArticle")
        self.labelLstArticle = QtWidgets.QLabel(Dialog)
        self.labelLstArticle.setGeometry(QtCore.QRect(20, 10, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.labelLstArticle.setFont(font)
        self.labelLstArticle.setObjectName("labelLstArticle")
        self.labelLstFacture = QtWidgets.QLabel(Dialog)
        self.labelLstFacture.setGeometry(QtCore.QRect(390, 10, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.labelLstFacture.setFont(font)
        self.labelLstFacture.setObjectName("labelLstFacture")
        self.textBrowserLstFacture = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserLstFacture.setGeometry(QtCore.QRect(390, 50, 351, 311))
        self.textBrowserLstFacture.setObjectName("textBrowserLstFacture")
        self.textBrowserLstUser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserLstUser.setGeometry(QtCore.QRect(20, 420, 351, 311))
        self.textBrowserLstUser.setObjectName("textBrowserLstUser")
        self.labelLstUser = QtWidgets.QLabel(Dialog)
        self.labelLstUser.setGeometry(QtCore.QRect(20, 380, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.labelLstUser.setFont(font)
        self.labelLstUser.setObjectName("labelLstUser")
        self.labelID = QtWidgets.QLabel(Dialog)
        self.labelID.setGeometry(QtCore.QRect(400, 410, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.labelID.setFont(font)
        self.labelID.setObjectName("labelID")
        self.labelID_2 = QtWidgets.QLabel(Dialog)
        self.labelID_2.setGeometry(QtCore.QRect(400, 450, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.labelID_2.setFont(font)
        self.labelID_2.setObjectName("labelID_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelLstArticle.setText(_translate("Dialog", "Liste des Articles :"))
        self.labelLstFacture.setText(_translate("Dialog", "Liste des Factures :"))
        self.labelLstUser.setText(_translate("Dialog", "Liste des Utilisateurs :"))
        self.labelID.setText(_translate("Dialog", "Code ID:"))
        self.labelID_2.setText(_translate("Dialog", "Object a supprimer:"))
