# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainPage.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 589)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.textBrowserInventaire = QTextBrowser(self.centralwidget)
        self.textBrowserInventaire.setObjectName(u"textBrowserInventaire")
        self.textBrowserInventaire.setGeometry(QRect(20, 60, 401, 481))
        self.labelTitre = QLabel(self.centralwidget)
        self.labelTitre.setObjectName(u"labelTitre")
        self.labelTitre.setGeometry(QRect(20, 20, 401, 31))
        font = QFont()
        font.setFamily(u"Comic Sans MS")
        font.setPointSize(15)
        self.labelTitre.setFont(font)
        self.buttonAjouter = QPushButton(self.centralwidget)
        self.buttonAjouter.setObjectName(u"buttonAjouter")
        self.buttonAjouter.setGeometry(QRect(450, 230, 151, 31))
        self.lineEditID = QLineEdit(self.centralwidget)
        self.lineEditID.setObjectName(u"lineEditID")
        self.lineEditID.setGeometry(QRect(570, 110, 201, 31))
        self.lineEditQuantite = QLineEdit(self.centralwidget)
        self.lineEditQuantite.setObjectName(u"lineEditQuantite")
        self.lineEditQuantite.setGeometry(QRect(570, 150, 201, 31))
        self.labelID = QLabel(self.centralwidget)
        self.labelID.setObjectName(u"labelID")
        self.labelID.setGeometry(QRect(450, 110, 121, 31))
        font1 = QFont()
        font1.setFamily(u"Comic Sans MS")
        font1.setPointSize(10)
        self.labelID.setFont(font1)
        self.labelQuantite = QLabel(self.centralwidget)
        self.labelQuantite.setObjectName(u"labelQuantite")
        self.labelQuantite.setGeometry(QRect(450, 150, 121, 31))
        self.labelQuantite.setFont(font1)
        self.textBrowserPanier = QTextBrowser(self.centralwidget)
        self.textBrowserPanier.setObjectName(u"textBrowserPanier")
        self.textBrowserPanier.setGeometry(QRect(450, 350, 321, 192))
        self.labelPanier = QLabel(self.centralwidget)
        self.labelPanier.setObjectName(u"labelPanier")
        self.labelPanier.setGeometry(QRect(450, 310, 321, 31))
        self.labelPanier.setFont(font)
        self.labelErreur = QLabel(self.centralwidget)
        self.labelErreur.setObjectName(u"labelErreur")
        self.labelErreur.setGeometry(QRect(450, 190, 321, 31))
        font2 = QFont()
        font2.setFamily(u"MS Shell Dlg 2")
        font2.setBold(True)
        font2.setWeight(75)
        self.labelErreur.setFont(font2)
        self.labelErreur.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.buttonRetirer = QPushButton(self.centralwidget)
        self.buttonRetirer.setObjectName(u"buttonRetirer")
        self.buttonRetirer.setGeometry(QRect(620, 230, 151, 31))
        self.buttonPayer = QPushButton(self.centralwidget)
        self.buttonPayer.setObjectName(u"buttonPayer")
        self.buttonPayer.setGeometry(QRect(450, 270, 151, 31))
        self.buttonFacture = QPushButton(self.centralwidget)
        self.buttonFacture.setObjectName(u"buttonFacture")
        self.buttonFacture.setGeometry(QRect(620, 270, 151, 31))
        self.labelFiltre = QLabel(self.centralwidget)
        self.labelFiltre.setObjectName(u"labelFiltre")
        self.labelFiltre.setGeometry(QRect(450, 20, 181, 31))
        font3 = QFont()
        font3.setFamily(u"Comic Sans MS")
        font3.setPointSize(13)
        self.labelFiltre.setFont(font3)
        self.comboBoxFiltre = QComboBox(self.centralwidget)
        self.comboBoxFiltre.addItem("")
        self.comboBoxFiltre.addItem("")
        self.comboBoxFiltre.addItem("")
        self.comboBoxFiltre.addItem("")
        self.comboBoxFiltre.setObjectName(u"comboBoxFiltre")
        self.comboBoxFiltre.setGeometry(QRect(450, 60, 201, 31))
        self.buttonFiltre = QPushButton(self.centralwidget)
        self.buttonFiltre.setObjectName(u"buttonFiltre")
        self.buttonFiltre.setGeometry(QRect(660, 60, 111, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.labelQuantite.raise_()
        self.textBrowserInventaire.raise_()
        self.labelTitre.raise_()
        self.buttonAjouter.raise_()
        self.lineEditID.raise_()
        self.lineEditQuantite.raise_()
        self.labelID.raise_()
        self.textBrowserPanier.raise_()
        self.labelPanier.raise_()
        self.labelErreur.raise_()
        self.buttonRetirer.raise_()
        self.buttonPayer.raise_()
        self.buttonFacture.raise_()
        self.labelFiltre.raise_()
        self.comboBoxFiltre.raise_()
        self.buttonFiltre.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.labelTitre.setText(QCoreApplication.translate("MainWindow", u"Liste des produits en vente", None))
        self.buttonAjouter.setText(QCoreApplication.translate("MainWindow", u"Ajout\u00e9 au panier", None))
        self.labelID.setText(QCoreApplication.translate("MainWindow", u"ID du produit:", None))
        self.labelQuantite.setText(QCoreApplication.translate("MainWindow", u"Quantit\u00e9:", None))
        self.labelPanier.setText(QCoreApplication.translate("MainWindow", u"Panier", None))
        self.labelErreur.setText(QCoreApplication.translate("MainWindow", u"* labelErreur", None))
        self.buttonRetirer.setText(QCoreApplication.translate("MainWindow", u"Retirer du panier", None))
        self.buttonPayer.setText(QCoreApplication.translate("MainWindow", u"Payer", None))
        self.buttonFacture.setText(QCoreApplication.translate("MainWindow", u"Voir mes factures", None))
        self.labelFiltre.setText(QCoreApplication.translate("MainWindow", u"Type de produit :", None))
        self.comboBoxFiltre.setItemText(0, QCoreApplication.translate("MainWindow", u"Tout type de produit", None))
        self.comboBoxFiltre.setItemText(1, QCoreApplication.translate("MainWindow", u"Potion", None))
        self.comboBoxFiltre.setItemText(2, QCoreApplication.translate("MainWindow", u"Sortillege", None))
        self.comboBoxFiltre.setItemText(3, QCoreApplication.translate("MainWindow", u"Pierre Magique", None))

        self.buttonFiltre.setText(QCoreApplication.translate("MainWindow", u"Filtrer", None))
    # retranslateUi

