# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'INTERFACEGRAPHIQUE/UI/MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowserInventaire = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserInventaire.setGeometry(QtCore.QRect(20, 60, 401, 441))
        self.textBrowserInventaire.setObjectName("textBrowserInventaire")
        self.labelTitre = QtWidgets.QLabel(self.centralwidget)
        self.labelTitre.setGeometry(QtCore.QRect(20, 20, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.labelTitre.setFont(font)
        self.labelTitre.setObjectName("labelTitre")
        self.buttonAjouter = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAjouter.setGeometry(QtCore.QRect(450, 190, 151, 31))
        self.buttonAjouter.setObjectName("buttonAjouter")
        self.lineEditID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditID.setGeometry(QtCore.QRect(570, 60, 161, 31))
        self.lineEditID.setObjectName("lineEditID")
        self.lineEditQuantite = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditQuantite.setGeometry(QtCore.QRect(570, 100, 161, 31))
        self.lineEditQuantite.setObjectName("lineEditQuantite")
        self.labelID = QtWidgets.QLabel(self.centralwidget)
        self.labelID.setGeometry(QtCore.QRect(450, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labelID.setFont(font)
        self.labelID.setObjectName("labelID")
        self.labelQuantite = QtWidgets.QLabel(self.centralwidget)
        self.labelQuantite.setGeometry(QtCore.QRect(450, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labelQuantite.setFont(font)
        self.labelQuantite.setObjectName("labelQuantite")
        self.textBrowserPanier = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserPanier.setGeometry(QtCore.QRect(450, 310, 321, 192))
        self.textBrowserPanier.setObjectName("textBrowserPanier")
        self.labelPanier = QtWidgets.QLabel(self.centralwidget)
        self.labelPanier.setGeometry(QtCore.QRect(450, 270, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.labelPanier.setFont(font)
        self.labelPanier.setObjectName("labelPanier")
        self.labelErreur = QtWidgets.QLabel(self.centralwidget)
        self.labelErreur.setGeometry(QtCore.QRect(430, 140, 321, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.labelErreur.setFont(font)
        self.labelErreur.setStyleSheet("color: rgb(255, 0, 0);")
        self.labelErreur.setObjectName("labelErreur")
        self.buttonRetirer = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRetirer.setGeometry(QtCore.QRect(620, 190, 151, 31))
        self.buttonRetirer.setObjectName("buttonRetirer")
        self.buttonPayer = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPayer.setGeometry(QtCore.QRect(450, 230, 151, 31))
        self.buttonPayer.setObjectName("buttonPayer")
        self.buttonFacture = QtWidgets.QPushButton(self.centralwidget)
        self.buttonFacture.setGeometry(QtCore.QRect(620, 230, 151, 31))
        self.buttonFacture.setObjectName("buttonFacture")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitre.setText(_translate("MainWindow", "Liste des produits en vente"))
        self.buttonAjouter.setText(_translate("MainWindow", "Ajouté au panier"))
        self.labelID.setText(_translate("MainWindow", "ID du produit:"))
        self.labelQuantite.setText(_translate("MainWindow", "Quantité:"))
        self.labelPanier.setText(_translate("MainWindow", "Panier"))
        self.labelErreur.setText(_translate("MainWindow", "* labelErreur"))
        self.buttonRetirer.setText(_translate("MainWindow", "Retirer du panier"))
        self.buttonPayer.setText(_translate("MainWindow", "Payer"))
        self.buttonFacture.setText(_translate("MainWindow", "Voir mes factures"))
